# FLASH CATEGORIES
SUCCESS = "success"
ERROR = "error"
WARNING = "warning"

# LINIA LOTNICZA
LINIALOTNICZA_UN_NAZWA = "LINIALOTNICZA_UN_NAZWA"
# LOTNISKO
LOTNISKO_UN_IATA = "LOTNISKO_UN_IATA"
LOTNISKO_UN_NAZWA = "LOTNISKO_UN_NAZWA"
LOTNISKO_UN_ICAO = "LOTNISKO_UN_ICAO"
LOTNISKO_UN_GEO = "LOTNISKO_UN_GEO"
# PRODUCENT
PRODUCENT__UN = "PRODUCENT__UN"
# MODEL
MODEL_UN_NAZWA = "MODEL_UN_NAZWA"
# PAS
PAS__UN = "PAS__UN"
# KLASA
KLASA_UN_NAZWA = "KLASA_UN_NAZWA"
# PASAZER
PASAZER_UN_LOGIN = "PASAZER_UN_LOGIN"
PASAZER_UN_PESEL = "PASAZER_UN_PESEL"


# FLIGHTS
MINUTES_FOR_FLIGHT = 10
