# FLASH CATEGORIES
SUCCESS = "success"
ERROR = "error"


# LINIA LOTNICZA
LINIALOTNICZA_UN_NAZWA = "LINIALOTNICZA_UN_NAZWA"
# LOTNISKO
LOTNISKO_UN_IATA = "LOTNISKO_UN_IATA"
LOTNISKO_UN_NAZWA = "LOTNISKO_UN_NAZWA"
LOTNISKO_UN_ICAO = "LOTNISKO_UN_ICAO"
LOTNISKO_UN_GEO = "LOTNISKO_UN_GEO"
# PRODUCENT
PRODUCENT__UN = "PRODUCENT__UN"
# MODEL
MODEL_UN_NAZWA = "MODEL_UN_NAZWA"
# PAS
PAS__UN = "PAS__UN"

